[package]
name = "demo"
version = "0.1.0"

[[app]]
name = "WebSocket"
main = "./src/WebSocket.lf"
target = "C"
platform = "Native"

[app.properties]
cmake-include="test.cmake"

[dependencies]
mqtt = {version=">=0.1", git="https://github.com/LF-Community/mqtt.git", tag="v0.1.2"}
websocket = {version=">=0.1", git="https://github.com/LF-Community/websocket.git", branch="dev"}
